apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nodejs
  template:
    metadata:
      labels:
        app: app1-nodejs
    spec:
      containers:
        - name: app1-nodejs
          image: acryouverifydev.azurecr.io/youverifyaksnodejsapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nodejs-loadbalancer-service
  labels:
    app: app1-nodejs
spec:
  type: LoadBalancer
  selector:
    app: app1-nodejs
  ports:
    - port: 80
      targetPort: 80



